name: React CI

on:
  push:
    branches: [ "main" ] 

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # Add or modify Node.js versions based on your project requirements

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run dev
    #- run: npm run build
    # You can add additional steps for your specific React project needs,
    # such as running tests, linting, etc.
    #- name: Run Tests
   #   run: npm dev
